"""Generates Assets/Scripts/Levels.cs from coordinate-based layouts (x right, y up)."""
import os


class Grid:
    def __init__(self, w, h):
        self.w, self.h = w, h
        self.g = [[' '] * w for _ in range(h)]

    def put(self, x, y, ch):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.g[y][x] = ch

    def rect(self, x0, y0, x1, y1, ch):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.put(x, y, ch)

    def row(self, x0, x1, y, ch):
        self.rect(x0, y, x1, y, ch)

    def rows(self):
        return [''.join(self.g[y]).rstrip() for y in range(self.h - 1, -1, -1)]


def level1():
    g = Grid(90, 16)
    g.row(0, 89, 0, '#')
    g.rect(0, 0, 0, 15, '#')
    g.put(3, 1, 'S')
    for x in (7, 9, 11):
        g.put(x, 2, '*')
    g.row(15, 19, 1, '#')
    g.row(17, 19, 2, '#')
    g.put(18, 4, '*')
    g.row(24, 27, 4, '#')
    g.put(25, 6, '*')
    g.row(26, 28, 1, '^')
    g.put(33, 1, 'C')
    g.put(34, 1, 'C')
    g.put(33, 2, 'C')
    g.put(38, 1, 'H')
    g.rect(42, 2, 62, 5, '#')
    for x in range(43, 62, 2):
        g.put(x, 1, '*')
    for x in (67, 69, 71, 73):
        g.put(x, 1, 'D')
    g.put(77, 1, 'B')
    g.row(80, 88, 6, '#')
    g.rect(89, 0, 89, 15, '#')
    g.put(79, 9, '*')
    g.put(85, 8, 'F')
    return g


def level2b():
    g = Grid(130, 20)
    base = 4
    g.row(0, 32, base, '#')
    g.rect(0, 0, 0, 19, '#')
    g.rect(0, 0, 129, base - 1, ' ')
    g.put(3, base + 1, 'S')
    for x in (7, 9):
        g.put(x, base + 2, '*')
    g.rect(15, base + 1, 15, base + 3, 'X')
    g.rect(15, base + 4, 15, 19, '#')
    for x in (19, 21, 23):
        g.put(x, base + 2, '*')
    g.row(33, 42, base - 1, '^')
    g.row(33, 42, base - 2, '#')
    for x in (35, 37, 39):
        g.put(x, base + 4, '*')
    g.row(43, 64, base, '#')
    g.put(45, base + 1, 'H')
    g.row(50, 52, base + 1, 'C')
    g.row(50, 51, base + 2, 'C')
    g.put(50, base + 3, 'C')
    g.row(53, 53, base + 1, 'C')
    g.put(58, base + 2, 'P')
    g.row(65, 74, base, 'X')
    g.row(65, 74, base - 4, '#')
    g.rect(64, 0, 64, base - 1, '#')
    g.rect(75, 0, 75, base, '#')
    for x in range(66, 74, 2):
        g.put(x, base - 3, '*')
    g.row(76, 96, base - 4, '#')
    g.row(65, 96, base - 4, '#')
    g.rect(76, base - 3, 96, base, ' ')
    g.row(75, 96, base - 4, '#')
    g.rect(75, base - 3, 75, base, ' ')
    g.rect(80, base - 3, 80, base - 2, 'X')
    g.put(85, base - 3, 'H')
    g.rect(88, base - 1, 110, base + 6, '#')
    for x in range(89, 110, 2):
        g.put(x, base - 3, '*')
    g.row(97, 129, base - 4, '#')
    g.rect(111, base - 3, 112, base + 6, ' ')
    g.row(113, 129, base - 4, '#')
    g.put(118, base - 3, 'B')
    g.rect(75, base, 75, 19, '#')
    g.row(121, 128, base + 2, '#')
    g.put(125, base + 4, 'F')
    g.rect(129, 0, 129, 19, '#')
    return g


def level3():
    g = Grid(140, 18)
    g.row(0, 139, 0, '#')
    g.rect(0, 0, 0, 17, '#')
    g.put(3, 1, 'S')
    for x in (7, 9, 11):
        g.put(x, 2, '*')
    g.rect(16, 1, 18, 17, 'G')
    for x in (21, 23):
        g.put(x, 2, '*')
    g.put(26, 1, 'H')
    g.row(30, 45, 0, '~')
    g.row(28, 47, -1, '#')
    for x in (33, 37, 41):
        g.put(x, 3, '*')
    g.put(50, 1, 'H')
    g.rect(54, 4, 80, 6, '#')
    for x in (60, 66, 72):
        g.put(x, 3, 'L')
    for x in (58, 63, 69, 75):
        g.put(x, 1, '*')
    g.put(84, 1, 'H')
    g.row(88, 104, 0, '^')
    g.row(88, 104, -1, '#')
    g.put(96, 9, 'O')
    g.row(92, 93, 3, '#')
    g.row(100, 101, 3, '#')
    g.put(92, 5, '*')
    g.put(100, 5, '*')
    g.put(108, 1, 'H')
    g.rect(112, 1, 113, 17, 'G')
    g.row(116, 125, 0, '~')
    g.put(128, 1, 'C')
    g.put(129, 1, 'C')
    g.put(128, 2, 'C')
    g.put(134, 2, 'F')
    g.rect(139, 0, 139, 17, '#')
    return g


def cs_rows(g):
    return ',\n'.join('            "' + r + '"' for r in g.rows())


def main():
    levels = [
        ("ROLL & BOUNCE", "jump,crouch", "ARROWS/A-D roll   SPACE jump   S crouch through tunnels", level1()),
        ("SPIN & GROW", "dash,grow", "SHIFT spin-dash breaks cracked walls   G grow: heavy, smashes floors", level2b()),
        ("BLINK & FREEZE", "teleport,freeze,invis", "T blink through glass   F freeze to skate lava   V vanish past lasers", level3()),
    ]
    out = ["// Generated by tools/gen_levels.py", "public static class Levels", "{",
           "    public struct Level { public string name, unlock, hint; public string[] map; }", "",
           "    public static readonly Level[] All =", "    {"]
    for name, unlock, hint, g in levels:
        out.append("        new Level { name = \"%s\", unlock = \"%s\", hint = \"%s\", map = new[]\n        {\n%s\n        } }," % (name, unlock, hint, cs_rows(g)))
    out += ["    };", "}", ""]
    path = os.path.join(os.path.dirname(__file__), '..', 'Assets', 'Scripts', 'Levels.cs')
    open(path, 'w').write('\n'.join(out))
    for _, _, _, g in levels:
        print('\n'.join(g.rows()))
        print('-' * 40)


main()
