// Generated by tools/gen_levels.py
public static class Levels
{
    public struct Level { public string name, unlock, hint; public string[] map; }

    public static readonly Level[] All =
    {
        new Level { name = "ROLL & BOUNCE", unlock = "jump,crouch", hint = "ARROWS/A-D roll   SPACE jump   S crouch through tunnels", map = new[]
        {
            "#                                                                                        #",
            "#                                                                                        #",
            "#                                                                                        #",
            "#                                                                                        #",
            "#                                                                                        #",
            "#                                                                                        #",
            "#                                                                              *         #",
            "#                                                                                    F   #",
            "#                                                                                        #",
            "#                        *                                                      ##########",
            "#                                         #####################                          #",
            "#                 *     ####              #####################                          #",
            "#                                         #####################                          #",
            "#      * * *     ###             C        #####################                          #",
            "#  S           #####      ^^^    CC   H    * * * * * * * * * *     D D D D   B           #",
            "##########################################################################################"
        } },
        new Level { name = "SPIN & GROW", unlock = "dash,grow", hint = "SHIFT spin-dash breaks cracked walls   G grow: heavy, smashes floors", map = new[]
        {
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #                                                     #",
            "#              #                                                           #            #######################                  #",
            "#              #                                                           #            #######################                  #",
            "#              #                   * * *                                   #            #######################              F   #",
            "#              X                                  C                        #            #######################                  #",
            "#      * *     X   * * *                          CC      P                #            #######################          #########",
            "#  S           X                             H    CCCC                     #            #######################                  #",
            "#################################          ######################XXXXXXXXXX#            #######################                  #",
            "                                 ^^^^^^^^^^                     #                       #######################                  #",
            "                                 ##########                     #               X                                                #",
            "                                                                # * * * *       X    H   * * * * * * * * * * *        B          #",
            "                                                                ##################################################################"
        } },
        new Level { name = "BLINK & FREEZE", unlock = "teleport,freeze,invis", hint = "T blink through glass   F freeze to skate lava   V vanish past lasers", map = new[]
        {
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                             O               GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                                                                             GG                         #",
            "#               GGG                                   ###########################                               GG                         #",
            "#               GGG                                   ###########################           *       *           GG                         #",
            "#               GGG                                   ###########################                               GG                         #",
            "#               GGG              *   *   *                  L     L     L                   ##      ##          GG                         #",
            "#      * * *    GGG  * *                                                                                        GG              C     F    #",
            "#  S            GGG       H                       H       *    *     *     *        H                       H   GG              CC         #",
            "##############################~~~~~~~~~~~~~~~~##########################################^^^^^^^^^^^^^^^^^###########~~~~~~~~~~##############"
        } },
    };
}
