name: Deploy Game to Itch.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip the Unity WebGL build
        run: cd webgl && zip -r ../game.zip .

      - name: Deploy with Butler
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: game
          ITCH_USER: slavastar
          PACKAGE: game.zip
